export default [{
  name: 'http简介',
  path: '/http/introduce'
}, {
  name: 'http是什么？',
  path: '/http/info'
}, {
  name: 'URI（统一资源标识符）',
  path: '/http/uri'
}, {
  name: 'TCP/IP 协议',
  path: '/http/tcpip'
}, {
  name: 'DNS（域名系统）',
  path: '/http/dns'
}, {
  name: 'http请求过程',
  path: '/http/process'
}, {
  name: 'http报文',
  path: '/http/message'
}, {
  name: 'http请求方法',
  path: '/http/method'
}, {
  name: 'http状态码',
  path: '/http/code'
}, {
  name: 'http的特点',
  path: '/http/feature'
}, {
  name: 'http大文件传输',
  path: '/http/bigFiles'
}, {
  name: 'http链接管理',
  path: '/http/connection'
}, {
  name: 'http重定向',
  path: '/http/redirect'
}, {
  name: 'http的Cookie机制',
  path: '/http/cookie'
}, {
  name: 'http缓存控制',
  path: '/http/cache'
}]
